name: deploy

on:
  push:
    branches:
      - 'master'

# Allow one concurrent deployment
concurrency:
  group: "deploy"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Deploy to server
        run : |
          sshpass -p '${{ secrets.SSH_PASSWORD }}' ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_URL }} 'cd $HOME/nuit-de-l-info && git pull && yarn build && rm -rf /var/www/{{ secrets.SSH_URL }}/* && cp -r dist/* /var/www/{{ secrets.SSH_URL }}/'
